apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7ImF1dGgiOiJSMjlvWVhKVFlYSnZlV0Z1T21kb2NGOTJNRVZqYTNGelZXRlNRVlF4ZFhwSlJtOTFXV2swTkRSR2NrTnhhRTB5WlRWVVVFST0ifX19
type: kubernetes.io/dockerconfigjson
